# Generated by Django 6.0.7 on 2026-08-31 23:05

import accounts.models
import accounts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document', models.FileField(blank=True, null=True, storage=accounts.models.identity_document_storage, upload_to=accounts.models.identity_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), accounts.validators.validate_document_size], verbose_name='documento de identidad')),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='estado')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'solicitud de verificación',
                'verbose_name_plural': 'solicitudes de verificación',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('seller',), name='one_pending_request_per_seller')],
            },
        ),
    ]
