# Generated by Django 6.0.7 on 2026-08-05 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('refurbished', 'Reacondicionado'), ('used', 'Usado'), ('for_parts', 'Para repuestos')], max_length=20, verbose_name='estado del artículo')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio inicial')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio actual')),
                ('closing_date', models.DateTimeField(verbose_name='fecha de cierre')),
                ('state', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='estado')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='auctions.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'subasta',
                'verbose_name_plural': 'subastas',
                'ordering': ['-published_at'],
            },
        ),
    ]
