# Generated by Django 6.0.7 on 2026-08-08 01:48

import auctions.models
import auctions.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=auctions.models.photograph_upload_path, validators=[auctions.validators.validate_photograph_size], verbose_name='fotografía')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='orden de presentación')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographs', to='auctions.auction', verbose_name='subasta')),
            ],
            options={
                'verbose_name': 'fotografía',
                'verbose_name_plural': 'fotografías',
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('auction', 'display_order'), name='unique_display_order_per_auction')],
            },
        ),
    ]
