# Generated by Django 6.0.7 on 2026-08-10 21:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_photograph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='monto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction', verbose_name='subasta')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='pujador')),
            ],
            options={
                'verbose_name': 'puja',
                'verbose_name_plural': 'pujas',
                'ordering': ['-amount', 'timestamp'],
            },
        ),
    ]
